version: '3.8'

services:
  quiz-session-service:
    build:
      context: ../src/quiz-session-service
      dockerfile: Dockerfile
    ports:
      - "5000:80"      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ASPNETCORE_URLS=http://+:80
    networks:
      - infrastructure-network
  notifier-worker:
    build:
      context: ../src/communication-services
      dockerfile: Dockerfile
    ports:
      - "6000:80"      
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ASPNETCORE_URLS=http://+:80
    networks:
      - infrastructure-network    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - infrastructure-network

networks:
  infrastructure-network:
    driver: bridge
